### PR TITLE
added daemon mode for unix-like systems

### PR DESCRIPTION
**Pull request by mosajjal**
It's especially helpful for those of us not wanting to spawn it on a damn screen command :-) very simple double fork without a need for any library as well.

### CODE REVIEW

**Comment by qwj** [comment]
It is more complex than double fork() to make a daemon. You should redirect standard output stdin/stdout/stderr to /dev/null to make a clean environment. Seems there is a module "python-daemon" that can make these complex jobs.

**Comment by mosajjal** [comment]
you're right but the whole point of this minimal patch is, if I run `pproxy` from the command line in daemon mode and then exit the terminal, `pproxy` will continue to run. Also service managers such as `systemd` or `upstart` would get the `stdout` and `stderr` automatically and save them inside the journal/log files

**Comment by qwj** [comment]
If the stdout doesn't redirect, it seems that in some cases the terminal won't exit.
The whole solution is:
https://www.python.org/dev/peps/pep-3143/
I think we can use python-daemon module to have better daemon functions.

**Comment by mosajjal** [comment]
using python-daemon, which I've used before and is excellent, is a complete solution. But I was worried about this app getting bloated by extra modules. After all, the goal of this project was to be minimal. 

How about putting stdout and stderr to a file (possibly pproxy.log file in the same directory) like this:

```
import sys
sys.stdout = open('pproxy.log', 'a')
sys.stderr = open('pproxy.log', 'a')
```

**Comment by qwj** [comment]
Yes, the goal of this project is to be minimal. I think we can add python-daemon as optional module to import. When "-d" is triggered, try import python-module, if failed, give user suggestion to install python-module to use "-d" feature.
Do you think it is a good design?

**Comment by mosajjal** [comment]
Yeah having an optional dependency will help managing the project better. here's a basic python question though: python-daemon uses context managers to create a daemon. How can we switch it on/off based on a boolean variable?

**Comment by qwj** [comment]
python "with" context is equal to call __enter__()/__exit__() at the beginning and the end

**Comment by mosajjal** [comment]
Cool! So I’ll close this one and we’ll open another one for Daemon. I’ll do it if I get the time this week

**Pull request closed without merging**
